apiVersion: apps/v1
kind: Deployment
metadata:
  name: point
  labels:
    app: point
spec:
  replicas: 1
  selector:
    matchLabels:
      app: point
  template:
    metadata:
      labels:
        app: point
        sidecar.istio.io/inject: "true" 
    spec:
      containers:
        - name: point
          image: "project20registry.azurecr.io/point:v13"
          ports:
            - containerPort: 8084

          env:
            - name: SERVER_ADDRESS
              value: "0.0.0.0"
            - name: SPRING_PROFILES_ACTIVE
              value: docker 

          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8084
            initialDelaySeconds: 90
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8084
            initialDelaySeconds: 240
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 5
