package miniprojectjo.domain;

// import com.fasterxml.jackson.databind.ObjectMapper; // Not used, remove
import java.time.LocalDate; // Not used, remove
import java.util.Collections; // Not used, remove
import java.util.Date; // Not used, remove
import java.util.List; // Not used, remove
import java.util.Map; // Not used, remove
import javax.persistence.*;
import lombok.Data; // Keep for getters, setters, etc.
import lombok.NoArgsConstructor; // Explicitly adding for clarity with @Data
import lombok.AllArgsConstructor; // Explicitly adding for clarity with @Data (if needed)

import miniprojectjo.PointApplication;
import miniprojectjo.domain.OutOfPoint;
import miniprojectjo.domain.PointBought;
import miniprojectjo.domain.PointDecreased;
import miniprojectjo.domain.PointRegistered;

@Entity
@Table(name = "Point_table")
@Data
@NoArgsConstructor // Ensures a no-arg constructor is generated by Lombok
@AllArgsConstructor // Generates a constructor with all fields (useful if needed elsewhere)
//<<< DDD / Aggregate Root
public class Point {

    @Id
    private String id;

    // 현재 보유 포인트 (초기 0)
    private int point = 0; // 'int' type, initialized to 0 by default and explicitly here

    private Boolean isSubscribe;

    @Embedded
    private UserId userId;

    @Embedded
    private SubscriptionId subscriptionId;

    // Explicit no-arg constructor is redundant with @NoArgsConstructor from Lombok,
    // but keeping it with explicit initialization for clarity as it was before.
    // However, for clean code, if using @NoArgsConstructor, this can be removed.
    // For this context, I'll keep the Lombok annotations and remove the manual one.
    /*
    public Point() {
        this.point = 0; // Already handled by 'private int point = 0;' and @NoArgsConstructor
    }
    */

    // 포인트 충전
    public void chargePoint(int amount) {
        if (amount <= 0) {
            throw new IllegalArgumentException("충전할 포인트는 0보다 커야 합니다.");
        }
        this.point += amount;
    }

    public static PointRepository repository() {
        return PointApplication.applicationContext.getBean(PointRepository.class);
    }

    // // 회원 가입 시 포인트 지급 (미구현 템플릿) - Keep commented as it was
    // public static void gainRegisterPoint(UserRegistered userRegistered) {
    //     // TODO: 구현
    //     System.out.println("##### KAFKA MESSAGE RECEIVED, UserRegistered : " + userRegistered.getId() + " #####");
    //     // 1) 새 포인트 객체 생성
    //     Point point = new Point();
    //     // 추가
    //     point.setId(String.valueOf(userRegistered.getId()));
    //     // 2) 사용자 ID 세팅 (UserRegistered 이벤트의 필드 이름에 맞춰 수정)
    //     point.setUserId(new UserId(String.valueOf(userRegistered.getId())));
    //     // 3) 초기 포인트 지급 (예: 1000 포인트)
    //     point.setPoint(1000);
    //     // 4) 구독 상태 초기화 (예: false)
    //     point.setIsSubscribe(false);
    //     // 5) 저장
    //     repository().save(point);
    //     // 6) PointRegistered 이벤트 발행
    //     PointRegistered pointRegistered = new PointRegistered(point);
    //     pointRegistered.publishAfterCommit();
    // }

    // 구독료 결제 시 포인트 차감
    public static void decreasePoint(SubscriptionApplied subscriptionApplied) {

        // 1) 이벤트에서 정보 꺼내기
        UserId userIdValue     = subscriptionApplied.getUserId();
        int    subscriptionCost = subscriptionApplied.getCost();

        // 2) 포인트 레코드 조회
        repository().findByUserId(userIdValue)
            .ifPresentOrElse(point -> {

                // 3‑1) 포인트 부족
                if (point.getPoint() < subscriptionCost) {
                    OutOfPoint outOfPoint = new OutOfPoint(point);
                    outOfPoint.publishAfterCommit();
                    return;
                }

                // 3‑2) 차감 후 저장
                point.setPoint(point.getPoint() - subscriptionCost);
                repository().save(point);

                // 4) 차감 이벤트 발행
                PointDecreased pointDecreased = new PointDecreased(point);
                pointDecreased.publishAfterCommit();

            }, () -> {
                // 포인트 레코드가 없을 때
                OutOfPoint outOfPoint = new OutOfPoint(
                    new Point() {{
                        setUserId(userIdValue);
                        setPoint(0);
                    }}
                );
                outOfPoint.publishAfterCommit();
            });
    }

    // 상품·서비스 구매 시 포인트 차감
    public static void purchasePoint(PointBought pointBought) {

        // [수정] String → UserId 객체로 감싸기
        UserId userId = pointBought.getUserId();
        repository().findByUserId(userId).ifPresent(point -> {

            if (point.getPoint() < pointBought.getPoint()) {
                OutOfPoint outOfPoint = new OutOfPoint(point);
                outOfPoint.publishAfterCommit();
                return;
            }

            point.setPoint(point.getPoint() - pointBought.getPoint());
            repository().save(point);

            // --- !!! 이 부분들을 삭제하거나 주석 처리합니다 (무한 루프의 원인) !!! ---
            // pointBought.setId(point.getId());
            // pointBought.setPoint(point.getPoint());
            // pointBought.publishAfterCommit(); // <--- 이 라인 제거!!!
            // --- !!! 수정 끝 !!! ---
        });
    }
}
//>>> DDD / Aggregate Root